version: '3.4'
services:
  jenkins:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4083:8080
      - 50000:50000
    networks:
      - jenkins_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
networks:
  jenkins_network: